"""Add new columns on credential model

Revision ID: 835549b518a2
Revises: aa4e26c169a1
Create Date: 2020-01-28 11:10:09.186979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "835549b518a2"
down_revision = "aa4e26c169a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credentials",
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("credentials", sa.Column("citizen_id", sa.Text(), nullable=False))
    op.add_column("credentials", sa.Column("msisdn", sa.Text(), nullable=False))
    op.add_column("credentials", sa.Column("name", sa.Text(), nullable=True))
    op.add_column("credentials", sa.Column("username", sa.Text(), nullable=False))
    op.alter_column("credentials", "_password", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("credentials", "email", existing_type=sa.TEXT(), nullable=False)
    op.create_unique_constraint(None, "credentials", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "credentials", type_="unique")
    op.alter_column("credentials", "email", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("credentials", "_password", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("credentials", "username")
    op.drop_column("credentials", "name")
    op.drop_column("credentials", "msisdn")
    op.drop_column("credentials", "citizen_id")
    op.drop_column("credentials", "additional_data")
    # ### end Alembic commands ###
